# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, PBL4):
        PBL4.setObjectName("PBL4")
        PBL4.resize(1226, 785)
        self.btnStart = QtWidgets.QToolButton(PBL4)
        self.btnStart.setGeometry(QtCore.QRect(110, 670, 131, 61))
        self.btnStart.setObjectName("btnStart")
        self.btnExit = QtWidgets.QToolButton(PBL4)
        self.btnExit.setGeometry(QtCore.QRect(370, 670, 131, 61))
        self.btnExit.setObjectName("btnExit")
        self.GroupCam = QtWidgets.QGroupBox(PBL4)
        self.GroupCam.setGeometry(QtCore.QRect(29, 20, 641, 611))
        self.GroupCam.setObjectName("GroupCam")
        self.image_label = QtWidgets.QLabel(self.GroupCam)
        self.image_label.setGeometry(QtCore.QRect(30, 40, 571, 551))
        self.image_label.setObjectName("image_label")
        self.List = QtWidgets.QGroupBox(PBL4)
        self.List.setGeometry(QtCore.QRect(710, 20, 481, 611))
        self.List.setObjectName("List")
        self.listvipham = QtWidgets.QLabel(self.List)
        self.listvipham.setGeometry(QtCore.QRect(0, 60, 481, 551))
        self.listvipham.setObjectName("listvipham")
        self.btnXuatfile = QtWidgets.QToolButton(PBL4)
        self.btnXuatfile.setGeometry(QtCore.QRect(910, 670, 131, 61))
        self.btnXuatfile.setObjectName("btnXuatfile")

        self.retranslateUi(PBL4)
        QtCore.QMetaObject.connectSlotsByName(PBL4)

    def retranslateUi(self, PBL4):
        _translate = QtCore.QCoreApplication.translate
        PBL4.setWindowTitle(_translate("PBL4", "PBL4"))
        self.btnStart.setToolTip(_translate("PBL4", "Start"))
        self.btnStart.setText(_translate("PBL4", "Start"))
        self.btnExit.setToolTip(_translate("PBL4", "Start"))
        self.btnExit.setText(_translate("PBL4", "Exit"))
        self.GroupCam.setTitle(_translate("PBL4", "Camera"))
        self.image_label.setText(_translate("PBL4", "image_label"))
        self.List.setTitle(_translate("PBL4", "List Vi Phạm"))
        self.listvipham.setText(_translate("PBL4", "listvipham"))
        self.btnXuatfile.setToolTip(_translate("PBL4", "Start"))
        self.btnXuatfile.setText(_translate("PBL4", "Xuất Excel"))
        
